export const customTrLocale = {
    firstDayOfWeek: 1, // Monday as the first day of the week
    weekdays: {
      shorthand: ["Paz", "Pzt", "Sal", "Çar", "Per", "Cum", "Cmt"],
      longhand: [
        "Pazar",
        "Pazartesi",
        "Salı",
        "Çarşamba",
        "Perşembe",
        "Cuma",
        "Cumartesi",
      ],
    },
    months: {
      shorthand: [
        "Oca",
        "Şub",
        "Mar",
        "Nis",
        "May",
        "Haz",
        "Tem",
        "Ağu",
        "Eyl",
        "Eki",
        "Kas",
        "Ara",
      ],
      longhand: [
        "Ocak",
        "Şubat",
        "Mart",
        "Nisan",
        "Mayıs",
        "Haziran",
        "Temmuz",
        "Ağustos",
        "Eylül",
        "Ekim",
        "Kasım",
        "Aralık",
      ],
    },
    ordinal: () => ".",
    rangeSeparator: " - ",
    weekAbbreviation: "Hf",
    scrollTitle: "Kaydırmak için tekerleği kullanın",
    toggleTitle: "Aç/kapat için tıklayın",
    amPM: ["ÖÖ", "ÖS"],
  };